version: '3.8'

services:
  h2:
    image: oscarfonts/h2
    ports:
      - "9092:1521"
      - "8082:81"
    volumes:
      - ./h2-data:/opt/h2-data
    environment:
      - H2_OPTIONS=-tcp -tcpAllowOthers -ifNotExists -baseDir /opt/h2-data

  redis:
    image: redis
    ports:
      - "6379:6379"

  jinkshower_1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=container
    depends_on:
      - redis
      - h2

  jinkshower_2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=container
    depends_on:
      - redis
      - h2
