spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  sql:
    init:
      schema-locations: classpath:initialize_table.sql
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.type.descriptor.sql:
      BasicBinder: TRACE
    org.springframework: DEBUG
