spring:
  datasource:
    url: jdbc:h2:tcp://h2:1521/./testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  data:
    redis:
      host: redis
      port: 6379
  sql:
    init:
      mode: always
