spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.type.descriptor.sql:
      BasicBinder: TRACE
    org.springframework: DEBUG
