name: cd

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 자바를 설치합니다.
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: "corretto"

      - name: Gradle을 캐싱합니다.
        uses: actions/cache@v3
        with:
          path: |
            .gradle/caches
            .gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # gradle chmod
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up environment variables
        run: |
          touch ./src/main/resources/application-prod.yml
          echo "${{ secrets.APPLICATION_PROD_YML }}" > ./src/main/resources/application-prod.yml
          cat ./src/main/resources/application-prod.yml

      # gradle build
      - name: Build with Gradle
        run: ./gradlew build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_EMAIL }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/session-cluster:latest

      ## deploy
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PUBLIC_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          port: ${{ secrets.WAS_SSH_PORT }}
          password: ${{ secrets.WAS_PASSWORD }}
          script: |
            docker-compose -f docker-compose-hiyen.yml down
            docker-compose -f docker-compose-hiyen.yml pull app
            docker-compose -f docker-compose-hiyen.yml build
            docker-compose -f docker-compose-hiyen.yml up -d
            docker image prune -a
